Lists: ordered, mutable, allows duplicate elements

Tuples: ordered, imutable, allows duplicate elements

Dict: Key-Value pairs, unordered, mutable

Sets: unordered, mutable, no duplicates

Strings: ordered, imutable, text representation

immutable(cannot be altered from index Ex. string[0] = 'x')
(Strings & Tuples)

# Strings

In [95]:
my_string = 'Hello World'
list1 = ['how', 'are', 'you', 'doing']


if 'ell' in my_string:
    print('Yes', '\n')
else:
    print('No')

print(my_string[::-1], '\n') # reverse string
print(my_string.split(), '\n') # Splits at space
print(my_string.find('lo'), '\n') # finds index of string
print(my_string.count('p'), '\n') # counts elements
print(my_string.replace('World', 'Universe'), '\n')
print(''.join(list1)) # join list to a string




Yes 

dlroW olleH 

['Hello', 'World'] 

3 

0 

Hello Universe 

howareyoudoing


In [111]:
# Inserting variables in strings

var = "Tom"
intvar = 3
fltvar = 3.864656

# old python
my_string = "the variable is %s" % var 
my_string2 = "the variable is %d" % intvar
my_string3 = "the variable is %.2f" % fltvar
# or newer way
my_string4 = f"the variable is {var} and {intvar} and {fltvar:.2f}"

print(my_string,'\n',my_string2, '\n', my_string3, '\n', my_string4)

the variable is Tom 
 the variable is 3 
 the variable is 3.86 
 the variable is Tom and 3 and 3.86


# Lists

In [335]:
my_list = [1,2,3,4,5,6,7,7,7]

print(sorted(list(set(my_list)), reverse=True)) # unique sorted list

#copy methods
cpy_list = my_list[:]
cpy_list2 = my_list.copy()
cpy_list3 = list(my_list)
# Not copy, exact match
cpy_list4 = my_list

[7, 6, 5, 4, 3, 2, 1]


In [306]:
# List comprhensions
mylist = [1,2,3,4,5,6,7]
b = [i*i for i in mylist]
c = [i*i for i in mylist if i > 1 for i in mylist if i > 2] # Nested and conditional comprehension
''' Same as 
for i in mylist:
    if i > 1:
        for i in mylist:
            if i > 2:
                i*i
'''
print(mylist, b, c, sep='\n')


[1, 2, 3, 4, 5, 6, 7]
[1, 4, 9, 16, 25, 36, 49]
[9, 16, 25, 36, 49, 9, 16, 25, 36, 49, 9, 16, 25, 36, 49, 9, 16, 25, 36, 49, 9, 16, 25, 36, 49, 9, 16, 25, 36, 49]


In [ ]:
# Try and expections list
'''
try:
   ...
except FirstException:
   handle_first_one()

except SecondException:
   handle_second_one()

except (ThirdException, FourthException, FifthException) as e:
   handle_either_of_3rd_4th_or_5th()

except Exception:
   handle_all_other_exceptions()
   '''

# Tuples

In [151]:
mytuple = tuple(["Max", 28, "Boston"])

mytuple2 = ('a', 'p', 'p', 'l', 'e')
# Cannot assign tuples like ''mytuple[0] = "Tim"''
# Easy check tuple
if "Max" in mytuple:
    print("Yes")
else:
    print("No")

print(mytuple2.count('o')) # Count elements in tuple
print(mytuple2.count('p'))
print("\n", mytuple2.index('p')) #Find index of first instance

name, age, city = mytuple # setting tuples to variables
print(name, age, city)

Yes
0
2

 1
Max 28 Boston


In [31]:
my_tuple = [0,1,2,3,4]

i1, *i2, i3 = my_tuple

print(i1)
print(i2)
print(i3)

#Tuples are much more efffiencent than lists
import timeit

print("\n")
print(timeit.timeit(stmt="[0,1,2,3,4,5]", number=100000))
print(timeit.timeit(stmt="(0,1,2,3,4,5)", number=100000))

0
[1, 2, 3]
4


0.007545399999798974
0.0008022000001801644


# Dictionaries

In [61]:
mydict = {"name": "Max", "age": 28, "city": "New York"}
print(mydict, "\n")

try:
    print(mydict["name"],"\n")
except:
    print("Error")


for key in mydict:
    print(key)
print("\n")
for value in mydict.values():
    print(value)
print("\n")
for key,value in mydict.items():
    print(key, value)
print("\n")
for key,value in mydict.items():
    if "Max" == value:
        print(key, value)
    else:
        continue

# Accessing dict
mydict.get("name")


{'name': 'Max', 'age': 28, 'city': 'New York'} 

Max 

name
age
city


Max
28
New York


name Max
age 28
city New York


name Max


'Max'

In [46]:
# Updating dictionaries
mydict = {"name": "Max", "age": 28, "Email": "email@eail.com"}
my_dict2 = {"name":"Mary", "city":"Boston"}
# Or 
my_dict2ALT = dict(name="Mary", city="Boston")

mydict.update(my_dict2)
print(mydict)

{'name': 'Mary', 'age': 28, 'Email': 'email@eail.com', 'city': 'Boston'}


In [60]:
# Accessing dict
mydict.get("name")

'Max'

# Sets

In [77]:
myset = set("Hello")
print(myset)

myset.add(1)
myset.add(2)

print(myset)
myset.remove(2)
print("\n")
print(myset)

if 1 in myset:
    print('yes\n')

odds = {1,3,5,7,9}
evens = {0,2,4,6,8}
primes = {2,3,5,7}

#Combine numbers
u = odds.union(evens)
print(u, "Union of odds and evens\n")

# Same numbers
i = odds.intersection(primes)
print(i, "Intersection of odds and primes\n")

setA = {1,2,3,4,5,6,7,8,9}
setB = {1,2,3,10,11,12}
# Difference of sets
diff = setA.difference(setB)
print(diff, "Difference of A - B\n")
# Symmetric Difference
diff2 = setA.symmetric_difference(setB)
print(diff2, "No matching in either elements A or B")




{'H', 'o', 'l', 'e'}
{1, 2, 'H', 'e', 'l', 'o'}


{1, 'H', 'e', 'l', 'o'}
yes

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9} Union of odds and evens

{3, 5, 7} Intersection of odds and primes

{4, 5, 6, 7, 8, 9} Difference of A - B

{4, 5, 6, 7, 8, 9, 10, 11, 12} No matching in either elements A or B


# Collections

In [128]:
from collections import Counter # Counts characters

a = "aaaaabbbbccc"
my_counter = Counter(a)
print(my_counter)
print(my_counter.most_common(3)) # Finds top common elements 
print(list(my_counter.elements())) # puts string into list


Counter({'a': 5, 'b': 4, 'c': 3})
[('a', 5), ('b', 4), ('c', 3)]
['a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'c', 'c', 'c']


In [130]:
from collections import namedtuple 

# naming tuples to a class

Point = namedtuple('Point', 'x,y')
pt = Point(1,-4)
print(pt, '\n')
print(pt.x, pt.y)


Point(x=1, y=-4) 

1 -4


In [134]:
from collections import OrderedDict
# Remembers the order of the dict when created

ordered_dict = OrderedDict()

ordered_dict['b'] = 2
ordered_dict['c'] = 3
ordered_dict['d'] = 4
ordered_dict['a'] = 1
print(ordered_dict)

OrderedDict([('b', 2), ('c', 3), ('d', 4), ('a', 1)])


In [137]:
from collections import defaultdict
# defults the dict to int, list, float, so not to return
# a error if value is missing

d = defaultdict(int)
d['a'] = 1
d['b'] = 2
print(d['c'])

0


In [150]:
from collections import deque
d = deque()

d.append(1)
d.append(2)
print(d)
d.appendleft(3)
print(d)
d.pop()
print(d)
d.popleft()
print(d)
d.extendleft([4,5,6])
print(d)
d.extend([4,5,6])
print(d)
d.rotate(1)
print(d)
d.rotate(-1)
print(d)

deque([1, 2])
deque([3, 1, 2])
deque([3, 1])
deque([1])
deque([6, 5, 4, 1])
deque([6, 5, 4, 1, 4, 5, 6])
deque([6, 6, 5, 4, 1, 4, 5])
deque([6, 5, 4, 1, 4, 5, 6])


# Itertools

In [159]:
from itertools import product
# find product of two iterables

a = [1,2]
b = [3,4]
print(product(a,b))
print(list(product(a,b)))
a = [1,2]
b = [3]
print(list(product(a,b, repeat = 2)))

[(1, 3), (1, 4), (2, 3), (2, 4)]
[(1, 3, 1, 3), (1, 3, 2, 3), (2, 3, 1, 3), (2, 3, 2, 3)]


In [162]:
from itertools import permutations
# all possible orderings of a input

a = [1,2,3]
print(list(permutations(a)))
print(list(permutations(a, 2))) # telling length of perm (optional)

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]
[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]


In [165]:
from itertools import combinations, combinations_with_replacement
# make all possible combinations of a specified length

a = [1,2,3,4]

print(list(combinations(a, 2))) # comb with length of 2
print(list(combinations_with_replacement(a,2)))

[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]
[(1, 1), (1, 2), (1, 3), (1, 4), (2, 2), (2, 3), (2, 4), (3, 3), (3, 4), (4, 4)]


In [169]:
from itertools import accumulate
# makes a iterable of accumulated sums (addition)

a = [1,2,3,4]
print(a)
print(list(accumulate(a))) # accumulates in ascending order
# Or for multiplication
import operator
print(list(accumulate(a, func=operator.mul))) # Multiply

a = [1,2,5,3,4] # Will keep the max number through order
print(list(accumulate(a, func=max)))

[1, 2, 3, 4]
[1, 3, 6, 10]
[1, 2, 6, 24]
[1, 2, 5, 5, 5]


In [175]:
from itertools import groupby
# Groups a function to a variable

a = [1,2,3,4]
# Normal function
def smaller_than_3(x):
    return x < 3

group_obj = groupby(a, key=smaller_than_3)

for key, value in group_obj:
    print(key, list(value))

# Lambda function
group_obj = groupby(a, key=lambda x: x<3)
for key, value in group_obj:
    print(key, list(value))
# Dictionary Example
persons = [{'name': 'Tim', 'age': 25}, {'name': 'Dan', 'age': 25},
{'name': 'Lisa', 'age': 27}, {'name': 'Claire', 'age': 28}]

group_obj = groupby(persons, key=lambda x: x['age'])
for key, value in group_obj:
    print(key, list(value))

True [1, 2]
False [3, 4]
True [1, 2]
False [3, 4]
25 [{'name': 'Tim', 'age': 25}, {'name': 'Dan', 'age': 25}]
27 [{'name': 'Lisa', 'age': 27}]
28 [{'name': 'Claire', 'age': 28}]


In [184]:
from itertools import count, cycle, repeat

for i in count(10): #count(start_value) infinite loop
    print(i)
    if i == 20:
        break

a = [1,2,3]
count = 1
for i in cycle(a): # Will cycle through until you put stop method
    print(i, count)
    count += 1
    if count == 10:
        break

for i in repeat(1, 7): #repeat(element to repeat, # of times)
    print(i)

10
11
12
13
14
15
16
17
18
19
20
1 1
2 2
3 3
1 4
2 5
3 6
1 7
2 8
3 9
1
1
1
1
1
1
1


# Lambda Functions
-  Map, filter, reduce

lambda variable: variable + expression 

map(function, sequence)

filter(function, sequence)

reduce(function, sequence)

In [193]:
# Lambda Functions
add10 = lambda x: x + 10
print(add10(5)) # turn any variable into a function

mult = lambda x,y: x*y # Multiple variables
print(mult(2,7))

points2D = [(1,2), (15,1), (5,-1), (10,4)]
sortedpoints = sorted(points2D) # by x values
sortedpoints2 = sorted(points2D, key=lambda x: x[1]) # by y values
sortedpoints3 = sorted(points2D, key=lambda x: x[0] + x[1]) # by sum of tuple

print(points2D)
print(sortedpoints)
print(sortedpoints2)
print(sortedpoints3)

15
14
[(1, 2), (15, 1), (5, -1), (10, 4)]
[(1, 2), (5, -1), (10, 4), (15, 1)]
[(5, -1), (15, 1), (1, 2), (10, 4)]
[(1, 2), (5, -1), (10, 4), (15, 1)]


In [ ]:
# Data frames lambda
prod['ListPrice'].apply(lambda x: x+100).tail(10) # Prod['ListPrice'] is considered x

prod['Color'].fillna('x').apply(lambda x: 'Bright ' + x).head(5) # fill all null in prod['Color']

In [201]:
# Mapping Function
a = [1,2,3,4,5] # sends function output to sequence ie (a)
b = map(lambda x: x*2, a)
print(list(b))

# same as
c = [x*2 for x in a]
print(c)

# Filter Funtion
a = [1,2,3,4,5,6] # runs sequence through filter and outputs accepted values depending on function
b = filter(lambda x: x%2==0, a)
print(list(b))

# same as
c = [x for x in a if x%2==0]
print(c)

# Reduce Function
from functools import reduce
a = [1,2,3,4,5] # Compounding sum of values from left to right, can be factorial if ordered from 1
            

product_a = reduce(lambda x,y: x*y, a)
print(product_a)

[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]
[2, 4, 6, 6]
[2, 4, 6, 6]
120


# Errors & Exceptions

In [206]:
try:
    a = 5 / 0
except Exception as e:
    print(e) # prints error
else:
    print('Everything is fine')
finally: # Always runs at end no matter what
    print('Cleaning up...')

division by zero
Cleaning up...


In [208]:
class ValueTooHighError(Exception):
    pass
class ValueTooSmallError(Exception):
    def __init__(self, message, value):
        self.message = message
        self.value = value
    
def test_value(x):
    if x > 100:
        raise ValueTooHighError('Value too high!', x)
    if x < 5:
        raise ValueTooSmallError('Value too small!', x)

try:
    test_value(1)
except ValueTooHighError as e:
    print(e)
except ValueTooSmallError as e:
    print(e.message, e.value)

Value too small! 1


# JSON
python == json

dict---object

list,tuple---array

string---string

int,long,float---number

True---true

False---false

None---null

In [213]:
import json
# Convert dict to json
person = {"name": "John", "age": 30, "city": "New York", "hasChildren": False, "titles": ["engineer", "programmer"]}

personJSONstr = json.dumps(person, indent=4, sort_keys=True)
print(personJSONstr)

# creates file
with open('person.json', 'w') as file:
    json.dump(person, file, indent=4)

# Load from string
person = json.loads(personJSONstr)
print(person, '\n')

# Load from file
with open('person.json', 'r') as file:
    person = json.load(file)
    print(person)

{
    "age": 30,
    "city": "New York",
    "hasChildren": false,
    "name": "John",
    "titles": [
        "engineer",
        "programmer"
    ]
}
{'age': 30, 'city': 'New York', 'hasChildren': False, 'name': 'John', 'titles': ['engineer', 'programmer']} 

{'name': 'John', 'age': 30, 'city': 'New York', 'hasChildren': False, 'titles': ['engineer', 'programmer']}


In [214]:
# Encoding custom objects 1
import json

class User:

    def __init__(self, name, age):
        self.name = name
        self.age = age

user = User('Max', 27)

def encode_user(o):
    if isinstance(o, User):
        return {'name': o.name, 'age': o.age, o.__class__.__name__:True}
    else:
        raise TypeError('Object of type User is not JSON serializable')
    
userJSON = json.dumps(user, default=encode_user)
print(userJSON)


{"name": "Max", "age": 27, "User": true}


In [219]:
# Encoding custom objects 2
from json import JSONEncoder
class UserEncoder(JSONEncoder):

    def default(self, o):
        if isinstance(o, User):
            return {'name': o.name, 'age': o.age, o.__class__.__name__:True}
        return JSONEncoder.default(self, o)   

userJSON = json.dumps(user, cls=UserEncoder)
#or userJSON = UserEncoder().encode(user)
print(userJSON)

# Decoding custom objects
def decode_user(dct):
    if User.__name__ in dct:
        return User(name=dct['name'], age=dct['age'])
    return dct    
user = json.loads(userJSON, object_hook=decode_user)
print(type(user))
print(user.name)

{"name": "Max", "age": 27, "User": true}
<class '__main__.User'>
Max


# Random Numbers

In [243]:
import random
# random.seed(x) makes random results reproducable

mylist = list("ABCDEFGH")

print(random.random()) # Random # from 0-1
print(random.uniform(1,10)) # Random float in the range
print(random.randint(1,10)) # Random int in the range
print(random.randrange(1,10)) # Will not include 10
print(random.normalvariate(0,1)) # (mu/mean, sigma/std)
print(random.choice(mylist)) # Randon element from list
print(random.choices(mylist, k=3)) # Not Unique sample
print(random.sample(mylist, 3)) # Unique random sample
random.shuffle(mylist) # Random shuffle
print(mylist)


0.6000687899786766
2.0966995793951533
9
3
-1.9420864763148158
H
['D', 'H', 'D']
['A', 'H', 'B']
['B', 'A', 'F', 'E', 'D', 'G', 'C', 'H']


In [250]:
import secrets
# generate random number
mylist = list("ABCDEFGH")
print(secrets.randbelow(10))
print(secrets.randbits(11))
print(secrets.choice(mylist))




3
1404
D


In [262]:
import numpy as np

number_grid = [[1,2,3],[4,5,6],[7,8,9],[0]]

print(np.random.rand(3)) # 1D array with 3 elements(floats)
print(np.random.rand(2,3))
print(np.random.randint(0,10, 3)) # Range 10 not included
print(np.random.randint(0,10, (2,3)))
np.random.shuffle(number_grid)
print(number_grid)


[0.19717293 0.32530496 0.89602239]
[[0.8515581  0.87842795 0.87316904]
 [0.69206005 0.47370139 0.15814517]]
[5 8 8]
[[5 1 4]
 [6 0 5]]
[[0], [4, 5, 6], [1, 2, 3], [7, 8, 9]]


# Decorators

In [264]:
# Base decorator example

def start_end_decorator(func):

    def wrapper():
        print('Start')
        func()
        print('End')
    return wrapper

@start_end_decorator
def print_name():
    print('Alex')

print_name()

Start
Alex
End


In [270]:
# Decorator Template
import functools

def my_decorator(func):

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        # Do something...
        result = func(*args, **kwargs)
        # Do something...
        return result
    return wrapper

@my_decorator
def add5(x):
    return x + 5

add5(5)



10

In [269]:
# Regular decorator

import functools

def repeat(num_times):
    def decorator_repeat(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            for _ in range(num_times):
                result = func(*args, **kwargs)
            return result
        return wrapper
    return decorator_repeat


@repeat(num_times=3)
def greet(name):
    print(f'Hello {name}')

greet('Alex')

Hello Alex
Hello Alex
Hello Alex


In [272]:
# Nested Decorator Function + debug decorator

def start_end_decorator(func):
    
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        print('Start')
        result = func(*args, **kwargs)
        print('End')
        return result
    return wrapper
def debug(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        args_repr = [repr(a) for a in args]
        kwargs_repr = [f'{k}={v!r}' for k, v in kwargs.items()]
        signature = ", ".join(args_repr + kwargs_repr)
        print(f'Calling {func.__name__}({signature})')
        result = func(*args, **kwargs)
        print(f'{func.__name__!r} returned {result!r}')
        return result
    return wrapper

@debug
@start_end_decorator
def say_hello(name):
    greeting = f'Hello {name}'
    print('Alex')
    return greeting

say_hello('Alex')

Calling say_hello('Alex')
Start
Alex
End
'say_hello' returned 'Hello Alex'


'Hello Alex'

In [275]:
# Class decorators

class CountCalls:

    def __init__(self, func):
        self.func = func
        self.num_calls = 0

    def __call__(self, *args, **kwargs):
        self.num_calls += 1
        print(f'This is executed {self.num_calls} times')
        return self.func(*args, **kwargs)

@CountCalls
def say_hello():
    print('Hello')

say_hello()
say_hello()

This is executed 1 times
Hello
This is executed 2 times
Hello


# Generators

In [282]:
def mygenerator():
    yield 1
    yield 2
    yield 3

g = mygenerator()

value = next(g)
print(value)
value = next(g)
print(value)
value = next(g)
print(value) # Will throw error if used a 4th time becuase we only have 3 yields


1
2
3


In [290]:
import sys

def firstn(n):
    nums = []
    num = 0
    while num < n:
        nums.append(num)
        num += 1
    return nums

def firstn_generator(n):
    num = 0
    while num < n:
        yield num
        num += 1

print(sum(firstn(10)))
print(sum(firstn_generator(10)), '\n')

# Much smaller and doesn't have to finish to get output
print(sys.getsizeof(firstn(1000000)))
print(sys.getsizeof(firstn_generator(1000000)), '\n')

# List comprehension
mygenerator = (i for i in range(10) if i % 2 == 0)
print(list(mygenerator))
mylist = [i for i in range(10) if i % 2 == 0]
print(mylist)

45
45 

8448728
112 

[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]


In [288]:
# Fibonacci Generator

def fibonacci(limit):
    a, b = 0, 1
    while a < limit:
        yield a
        a, b = b, a + b

fib = fibonacci(30)
for i in fib:
    print(i)

0
1
1
2
3
5
8
13
21


# Threading vs Multiprocessing

In [ ]:
# from multiprocessing import Process
# import os
# import time

# def square_numbers():
#     for i in range(100):
#         i + i
#         time.sleep(0.1)

# processes = []
# num_processes = os.cpu_count()

# # Create processes
# for i in range(num_processes)
#     p = Process(target=square_numbers)

# # start
# for p in processes:
#     p.start()

# # join
# for p in processes:
#     p.join()

# print('end main')


# Function Arguments

*args = Any number of positional arguments

**kwargs = Any number of keyword arguments

In [298]:
def foo(a, b, c, d=4):
    print(a, b, c, d)

foo(1,2,3)
foo(c=1, b=2, a=3)
foo(1,2,3,7)


1 2 3 4
3 2 1 4
1 2 3 7


In [301]:
def foo(a, b, *args, **kwargs):
    print(a, b)
    for arg in args:
        print(arg)
    for key in kwargs:
        print(key, kwargs[key])

foo(1,2,3,4,5, six=6, seven=7)

1 2
3
4
5
six 6
seven 7


# Pandas

In [1]:
import pandas as pd
prod = pd.read_csv('Data/Production.Product.csv', sep='\t')
titanic = pd.read_csv('Data/titanic.csv')
# Making Dataframe
lis1 = [1,2]
lis2 = [3,4]
all_lists = [lis1, lis2]
col = ['Col1', 'Col2']
ind = ['Row1', 'Row2']

df = pd.DataFrame(data=all_lists, index=ind, columns=col)
df

Col1  Col2
Row1     1     2
Row2     3     4

In [18]:
# Accessing row1, col2
list(df.iloc[0])
# df.at['Row1', 'Col2']
# df.iat[0, 1]

[1, 2]

In [15]:
# Access
titanic.iloc[20:25] # Rows 20-25
titanic.loc[1, 'Sex'] # Row, column exact match
titanic['Sex'] == 'male' # Get true/false statments for column
titanic[titanic['Sex'] == 'male'] # Print df of matching values
titanic[(titanic['Sex'] == 'male') & (titanic['Embarked'] == 'S')] # two or more values from different coloumns(And for both) less values
titanic[(titanic['Sex'] == 'male') | (titanic['Embarked'] == 'S')] # either or (more values)

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                         Braund, Mr. Owen Harris    male  22.0      1      0   
2                          Heikkinen, Miss. Laina  female  26.0      0      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                        Allen, Mr. William Henry    male  35.0      0      0   
5                                Moran, Mr. James    male   NaN      0      0   
..                                            ...     ...   ...    ...    ...   
886                         Montvila, Rev. Juozas    male  27.0      0      0   
887                  Graham, Miss. Margaret Edith  female  19.0      0      0   
888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2   
889                         Behr, Mr. Karl Howell    male  26.0      0      0   
890                           Dooley, Mr. Patrick    male  32.0      0      0   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500   NaN        S  
2    STON/O2. 3101282   7.9250   NaN        S  
3              113803  53.1000  C123        S  
4              373450   8.0500   NaN        S  
5              330877   8.4583   NaN        Q  
..                ...      ...   ...      ...  
886            211536  13.0000   NaN        S  
887            112053  30.0000   B42        S  
888        W./C. 6607  23.4500   NaN        S  
889            111369  30.0000  C148        C  
890            370376   7.7500   NaN        Q  

[780 rows x 12 columns]

In [317]:
# Manipulate
titanic.shape # Shape of DF, shape[0] = # of rows, shape[1] = # of columns
titanic.info() # Info, column datatype readout
titanic.describe() # Numbers of Data, .describe(percentiles=None, include=None, exclude=None, datetime_is_numeric=False).transpose()
titanic.describe(include='object') # prod.describe(include='all')
titanic.Survived.unique() # uniuqe values
titanic.nunique() # unique COUNT
titanic.sort_values('Pclass', ascending = False) # New dataframe sorted by that columns values
titanic.Embarked.value_counts() # value count
titanic.Survived.value_counts(dropna=False) # include nulls in value count
titanic.Embarked.value_counts(normalize=True) * 100 # value count percentage
titanic['gender'] = np.where(titanic['Sex'] == 'female', 1, 0) # create new column where condition is true (cond, True new value, False new value)
titanic.select_dtypes('object').columns # print object columns
titanic.select_dtypes('number').columns # print numeric columns
titanic.isnull().sum() # list all nulls in dataframe
titanic.fillna(value = {'Age': titanic['Age'].mean()}).head() # Fill missing value with mean
titanic.set_option('display.max_columns', None) # also do max rows but not reccomended
#titanic.index.name = 'column' -- change name of index

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  gender  
0      0         A/5 21171   7.2500   NaN        S       0  
1      0          PC 17599  71.2833   C85        C       1  
2      0  STON/O2. 3101282   7.9250   NaN        S       1  
3      0            113803  53.1000  C123        S       1  
4      0            373450   8.0500   NaN        S       0

In [322]:
# Group by statements
prod = pd.read_csv('Production.Product.csv', sep='\t')

# Max values of prices for different colors
prod[['Color', 'ListPrice']].groupby('Color').max().sort_values('ListPrice', ascending=False)

# here we can use 'x' as a dummy placeholder for nulls, simply to get consistent counts for all columns
prod.fillna(value='x').groupby(['Color']).count()

# Multindex column change
prod.fillna(value='x').groupby(by=['Class', 'Style']).count()[['Name']]




Name
Class Style      
H     U        64
      x        18
L     U        68
      x        29
M     U        22
      W        22
      x        24
x     M         7
      U        22
      W         6
      x       222

In [326]:
#agg to simulate describe
lis = ['count']
lis.append('mean')
prod.fillna(value={'Color': 'x'}).groupby('Color')['ListPrice'].agg(lis).sort_values(['mean'], ascending=False)

count         mean
Color                           
Red              38  1401.950000
Yellow           36   959.091389
Blue             26   923.679231
Silver           43   850.305349
Black            93   725.121075
Grey              1   125.000000
Silver/Black      7    64.018571
Multi             8    59.865000
x               248    16.864194
White             4     9.245000

# Miscellaneous

In [237]:
# Opening files, r = read, w = write, a = append to end
# r+ = read/write

employee_file = open("employees.txt", "r")
#print(employee_file.readable())

#print(employee_file.readline())

#print(employee_file.read())

#print(employee_file.readlines())

for e in employee_file.readlines():
    print(e)

employee_file.close()

Jim - Salesman

Dwight - Salesman

Pam - Receptionist

Michael - Manager

Oscar - Accountant


In [112]:
# Nested
number_grid = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [0]
]

print(number_grid[0][2])

for row in number_grid:
    print(row)

3
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[0]


In [113]:
for row in number_grid:
    print(row)
    for col in row:
        print(col)

[1, 2, 3]
1
2
3
[4, 5, 6]
4
5
6
[7, 8, 9]
7
8
9
[0]
0


In [4]:
i = 1
while i <= 10:
    print(i)
    i += 1
print('done')

1
2
3
4
5
6
7
8
9
10
done
